In [4]:
import numpy as np

In [6]:
arr = np.array([[2,4,6,8,10],[1,2,3,4,5],[4,0,6,2,5],[6,6,1,5,3],[7,5,1,6,5],[8,2,4,9,7]])
arr

array([[ 2,  4,  6,  8, 10],
       [ 1,  2,  3,  4,  5],
       [ 4,  0,  6,  2,  5],
       [ 6,  6,  1,  5,  3],
       [ 7,  5,  1,  6,  5],
       [ 8,  2,  4,  9,  7]])

In [11]:
arr[2:4,1:4]

array([[0, 6, 2],
       [6, 1, 5]])

In [14]:
arr1 = np.arange(1,37).reshape(6,6)
arr1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [24]:
arr1[2:4,5:]

array([[18],
       [24]])

In [26]:
arr1[:,::2]   #colon : denotes step

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23],
       [25, 27, 29],
       [31, 33, 35]])

In [28]:
arr1[::2,::2]

array([[ 1,  3,  5],
       [13, 15, 17],
       [25, 27, 29]])

# Boolean Indexing

In [30]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [31]:
data = np.random.randn(7, 4)
data

array([[ 0.92007882,  1.67216075, -1.14831033,  0.64896224],
       [-1.01942755,  1.27093617, -0.30604058,  0.68273665],
       [-2.49360816,  1.51087159,  0.26610178, -0.50489289],
       [-1.64920297, -0.97017194, -1.1119366 ,  0.13691048],
       [ 0.33023039,  0.22133709,  0.54103553,  0.93466981],
       [ 1.07559481, -0.69844299, -0.27675648, -0.5358178 ],
       [ 0.15690163,  0.15361888, -1.51726689,  1.48553929]])

In [32]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [33]:
data>1

array([[False,  True, False, False],
       [False,  True, False, False],
       [False,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [ True, False, False, False],
       [False, False, False,  True]])

In [34]:
data[data>1] 

array([1.67216075, 1.27093617, 1.51087159, 1.07559481, 1.48553929])

In [40]:
bol = np.array([True,False,False,False,False,True,False],dtype = "bool")
data[bol]

array([[ 0.92007882,  1.67216075, -1.14831033,  0.64896224],
       [ 1.07559481, -0.69844299, -0.27675648, -0.5358178 ]])

In [43]:
condition = names!="Bob"

In [45]:
data[~condition]

array([[ 0.92007882,  1.67216075, -1.14831033,  0.64896224],
       [-1.64920297, -0.97017194, -1.1119366 ,  0.13691048]])

In [46]:
data[~condition,3]

array([0.64896224, 0.13691048])

In [50]:
data

array([[ 0.92007882,  1.67216075, -1.14831033,  0.64896224],
       [-1.01942755,  1.27093617, -0.30604058,  0.68273665],
       [-2.49360816,  1.51087159,  0.26610178, -0.50489289],
       [-1.64920297, -0.97017194, -1.1119366 ,  0.13691048],
       [ 0.33023039,  0.22133709,  0.54103553,  0.93466981],
       [ 1.07559481, -0.69844299, -0.27675648, -0.5358178 ],
       [ 0.15690163,  0.15361888, -1.51726689,  1.48553929]])

In [49]:
data1 =np.arange(28).reshape(7,4)
print(data1)
print(condition)
data1[condition,1:3]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]
[False  True  True False  True  True  True]


array([[ 5,  6],
       [ 9, 10],
       [17, 18],
       [21, 22],
       [25, 26]])

In [51]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [52]:
cond = (names=='Bob') | (names=='Joe')
cond

array([ True,  True, False,  True, False,  True,  True])

In [54]:
data

array([[ 0.92007882,  1.67216075, -1.14831033,  0.64896224],
       [-1.01942755,  1.27093617, -0.30604058,  0.68273665],
       [-2.49360816,  1.51087159,  0.26610178, -0.50489289],
       [-1.64920297, -0.97017194, -1.1119366 ,  0.13691048],
       [ 0.33023039,  0.22133709,  0.54103553,  0.93466981],
       [ 1.07559481, -0.69844299, -0.27675648, -0.5358178 ],
       [ 0.15690163,  0.15361888, -1.51726689,  1.48553929]])

In [55]:
data[cond]

array([[ 0.92007882,  1.67216075, -1.14831033,  0.64896224],
       [-1.01942755,  1.27093617, -0.30604058,  0.68273665],
       [-1.64920297, -0.97017194, -1.1119366 ,  0.13691048],
       [ 1.07559481, -0.69844299, -0.27675648, -0.5358178 ],
       [ 0.15690163,  0.15361888, -1.51726689,  1.48553929]])

# Fancy Indexing

In [58]:
arr = np.empty((8,4))

for i in range(8):
    arr[i] = i

arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [59]:
arr[[1,2,3]]

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [60]:
arr[[4,0,1,7]]

array([[4., 4., 4., 4.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [7., 7., 7., 7.]])

In [61]:
arr[[4,0,1,2],[2,3,0,1]]

array([4., 0., 1., 2.])

In [62]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]
#1(0,3,1,2),5(0,3,1,2),7(0,3,1,2),2(0,3,1,2)
#(1,0)(1,3)(1,1)(1,2)(5,0)(5,3)(5,7)(5,2)()())()())()()()()()()().......

array([[1., 1., 1., 1.],
       [5., 5., 5., 5.],
       [7., 7., 7., 7.],
       [2., 2., 2., 2.]])

In [63]:
arr.T

array([[0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.]])

In [64]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])