In [1]:
import numpy as np

In [2]:
a = np.arange(5)
print(a)
print(a.dtype)

[0 1 2 3 4]
int32


In [3]:
a.shape

(5,)

In [4]:
a.ndim

1

In [5]:
data = np.random.randn(2,3)
data

array([[ 1.76957488, -0.65648214,  0.22929205],
       [ 0.70625966, -0.90912659,  1.53586596]])

In [6]:
data = np.random.randint(100)
data

91

In [7]:
data = np.random.rand()
data

0.1328078545089093

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [10]:
np.empty((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [11]:
np.array([[100]]).ndim

2

In [12]:
np.array([[[100],[99]],[[100],[99]]])

array([[[100],
        [ 99]],

       [[100],
        [ 99]]])

In [13]:
np.array([[[100],[99]],[[100],[99]]]).ndim

3

In [14]:
a = np.asarray([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [15]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
np.full((10),100)

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [17]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr[5]

5

In [19]:
arr[5:8]

array([5, 6, 7])

In [20]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr2d[2]

array([7, 8, 9])

In [22]:
arr2d[0][2]

3

In [23]:
arr2d[0, 2]

3

In [24]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [25]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
arr3d[1,0]

array([7, 8, 9])

In [27]:
arr3d[0,0,0]

1

In [28]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [29]:
data = np.random.randn(7, 4)
data

array([[ 1.22036462, -0.26888517, -0.65742923, -1.76159701],
       [ 1.71861168, -0.4758877 , -1.0319373 , -1.75793058],
       [ 0.40646764,  0.33393575, -0.37576403, -0.0862468 ],
       [ 0.26200619, -0.10248036, -0.79238266,  0.20899016],
       [-0.50971982, -0.01613287,  0.84889834,  1.24153587],
       [ 0.51466586, -2.26580657, -0.64442351, -1.41175551],
       [-0.30445536, -0.39492005, -0.27172801, -0.33549486]])

In [30]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [31]:
data[names == 'Bob']

array([[ 1.22036462, -0.26888517, -0.65742923, -1.76159701],
       [ 0.26200619, -0.10248036, -0.79238266,  0.20899016]])

In [32]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [33]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [34]:
arr = np.random.randn(6, 3)
arr

array([[-0.34862804,  0.37777739, -0.44926312],
       [ 0.34606668,  1.69423409,  0.04178645],
       [ 0.21829577,  0.38385628, -1.04880223],
       [ 0.7502712 , -0.19933185, -0.22909926],
       [ 2.3923509 , -1.09626818, -1.49180573],
       [-1.38808146, -1.5613286 ,  1.12575585]])

In [35]:
np.dot(arr.T, arr)

array([[ 8.50197657, -0.06655146, -5.36131265],
       [-0.06655146,  6.83977467, -0.57810361],
       [-5.36131265, -0.57810361,  4.8488666 ]])

In [36]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [37]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [38]:
arr.transpose()

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [39]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [40]:
arr = np.random.randn(6, 3)
arr

array([[-1.88078175,  0.88535212, -0.06051862],
       [ 0.21427971, -0.49279403,  1.57854112],
       [-0.84526622,  0.11183167,  0.71534137],
       [-0.96337615,  0.59738039,  1.62775294],
       [ 0.27001687,  0.36924967,  0.66684196],
       [ 1.79839015, -1.22422933,  0.26193261]])

In [41]:
np.abs(arr)

array([[1.88078175, 0.88535212, 0.06051862],
       [0.21427971, 0.49279403, 1.57854112],
       [0.84526622, 0.11183167, 0.71534137],
       [0.96337615, 0.59738039, 1.62775294],
       [0.27001687, 0.36924967, 0.66684196],
       [1.79839015, 1.22422933, 0.26193261]])

In [42]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
xarr

array([1.1, 1.2, 1.3, 1.4, 1.5])

In [43]:
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
yarr

array([2.1, 2.2, 2.3, 2.4, 2.5])

In [44]:
cond = np.array([True, False, True, True, False])
cond

array([ True, False,  True,  True, False])

In [45]:
result = [(x if c else y)
        for x, y, c in zip(xarr, yarr, cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [46]:
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [47]:
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
y = np.array([[4, 23, 2, 0],
             [12, 5, 64, 8],
             [14, 6, 73, 0],
             [3, 67, 90, 1]])
y

array([[ 4, 23,  2,  0],
       [12,  5, 64,  8],
       [14,  6, 73,  0],
       [ 3, 67, 90,  1]])

In [49]:
np.intersect1d(x, y)

array([0, 1, 2, 3, 4, 5, 6, 8])

In [50]:
np.union1d(x,y)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 14, 23, 64, 67,
       73, 90])

In [51]:
np.in1d(x,y)

array([ True,  True,  True,  True,  True,  True,  True, False,  True,
       False, False, False])

In [52]:
np.setdiff1d(x, y)

array([ 7,  9, 10, 11])

In [53]:
np.setxor1d(x, y)

array([ 7,  9, 10, 11, 12, 14, 23, 64, 67, 73, 90])

In [54]:
np.unique(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [55]:
np.unique(y)

array([ 0,  1,  2,  3,  4,  5,  6,  8, 12, 14, 23, 64, 67, 73, 90])

In [56]:
from numpy.linalg import inv, qr

In [57]:
X = np.random.randn(5, 5)
X

array([[-0.98628642,  0.60994185,  0.14314168, -0.64345462, -0.15732142],
       [-0.55025183, -1.60446522, -0.01126299, -0.97671624,  0.94417884],
       [ 1.06053532, -1.7585476 ,  1.58275382, -1.1256871 ,  0.0757902 ],
       [ 1.27466288, -0.8979058 ,  0.86130753,  1.55645183,  0.13979446],
       [-1.34605651,  0.49712871,  1.29449319,  1.41118042, -2.16352749]])

In [58]:
mat = X.T.dot(X)
mat

array([[ 5.83690672, -3.3974098 ,  0.89900086,  0.06266229,  2.8064271 ],
       [-3.3974098 ,  7.09219915, -2.80781204,  2.45820286, -2.94521358],
       [ 0.89900086, -2.80781204,  4.94328931,  1.30455713, -2.59346189],
       [ 0.06266229,  2.45820286,  1.30455713,  7.04915235, -3.74182595],
       [ 2.8064271 , -2.94521358, -2.59346189, -3.74182595,  5.62236156]])

In [59]:
inv(mat)

array([[ 0.54609225, -0.2964592 , -0.6787548 , -0.261597  , -0.91507436],
       [-0.2964592 ,  1.2520503 ,  1.58090997,  0.1348898 ,  1.62286087],
       [-0.6787548 ,  1.58090997,  2.46057352,  0.34216227,  2.5296681 ],
       [-0.261597  ,  0.1348898 ,  0.34216227,  0.34701794,  0.59001857],
       [-0.91507436,  1.62286087,  2.5296681 ,  0.59001857,  3.04429122]])

In [60]:
mat.dot(inv(mat))

array([[ 1.00000000e+00,  2.74793496e-16,  1.52459677e-16,
        -3.08844956e-16, -2.95823391e-16],
       [-4.49737597e-16,  1.00000000e+00, -5.49903759e-16,
         6.99377177e-17, -1.98841737e-16],
       [ 8.10002533e-17, -6.86734841e-18,  1.00000000e+00,
         1.25371913e-16,  2.29507551e-15],
       [ 4.04504432e-16, -1.16108146e-16,  1.12120662e-15,
         1.00000000e+00,  7.25411184e-16],
       [ 3.42490151e-16,  2.02579445e-16,  1.06451302e-15,
        -8.13660405e-17,  1.00000000e+00]])

In [61]:
q, r = qr(mat)

In [62]:
q

array([[-0.79210489, -0.45340317, -0.13436678,  0.32552838, -0.20729748],
       [ 0.46104984, -0.67589631,  0.05753755,  0.43832621,  0.36763676],
       [-0.12200006,  0.34993982, -0.67676762,  0.27612366,  0.57306144],
       [-0.00850367, -0.46325143, -0.43506285, -0.76038212,  0.13366057],
       [-0.38084978,  0.02302125,  0.57562219, -0.21789027,  0.68964222]])

In [63]:
r

array([[-7.36885579,  7.40429567, -1.63310002,  2.28969283, -5.3739283 ],
       [ 0.        , -5.44232859,  2.55599105, -4.58505647,  1.67350048],
       [ 0.        ,  0.        , -5.68822716, -5.97056515,  6.07290562],
       [ 0.        ,  0.        ,  0.        , -3.08662975,  0.52665086],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.22653622]])

In [64]:
np.random.seed(1234)

In [65]:
rng = np.random.RandomState(1234)

In [66]:
rng.randn(10)

array([ 0.47143516, -1.19097569,  1.43270697, -0.3126519 , -0.72058873,
        0.88716294,  0.85958841, -0.6365235 ,  0.01569637, -2.24268495])

In [67]:
x.strides

(16, 4)

In [68]:
ints = np.ones(10, dtype = 'uint16')
ints

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=uint16)

In [69]:
np.issubdtype(ints.dtype, np.integer)

True

In [70]:
np.float16.mro()

[numpy.float16,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 object]

In [71]:
arr = np.arange(15)

In [72]:
arr.reshape((5, -1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [73]:
arr = np.arange(12).reshape((3, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [74]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [75]:
arr.ravel('F')

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

In [76]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
arr2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [78]:
np.concatenate([arr1, arr2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [79]:
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [80]:
np.vstack((arr1, arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [81]:
np.hstack((arr1, arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [82]:
arr = np.random.randn(5, 2)
arr

array([[ 0.47143516, -1.19097569],
       [ 1.43270697, -0.3126519 ],
       [-0.72058873,  0.88716294],
       [ 0.85958841, -0.6365235 ],
       [ 0.01569637, -2.24268495]])

In [83]:
first, second, third = np.split(arr, (1, 3))

In [84]:
first

array([[ 0.47143516, -1.19097569]])

In [85]:
second

array([[ 1.43270697, -0.3126519 ],
       [-0.72058873,  0.88716294]])

In [86]:
third

array([[ 0.85958841, -0.6365235 ],
       [ 0.01569637, -2.24268495]])

In [87]:
arr = np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [88]:
arr1 = arr.reshape((3, 2))
arr1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [89]:
arr2 = np.random.randn(3, 2)
arr2

array([[ 1.15003572,  0.99194602],
       [ 0.95332413, -2.02125482],
       [-0.33407737,  0.00211836]])

In [90]:
np.r_[arr1, arr2]

array([[ 0.00000000e+00,  1.00000000e+00],
       [ 2.00000000e+00,  3.00000000e+00],
       [ 4.00000000e+00,  5.00000000e+00],
       [ 1.15003572e+00,  9.91946022e-01],
       [ 9.53324128e-01, -2.02125482e+00],
       [-3.34077366e-01,  2.11836468e-03]])

In [91]:
np.c_[np.r_[arr1, arr2], arr]

array([[ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [ 2.00000000e+00,  3.00000000e+00,  1.00000000e+00],
       [ 4.00000000e+00,  5.00000000e+00,  2.00000000e+00],
       [ 1.15003572e+00,  9.91946022e-01,  3.00000000e+00],
       [ 9.53324128e-01, -2.02125482e+00,  4.00000000e+00],
       [-3.34077366e-01,  2.11836468e-03,  5.00000000e+00]])

In [92]:
np.c_[1:6, -10:-5]

array([[  1, -10],
       [  2,  -9],
       [  3,  -8],
       [  4,  -7],
       [  5,  -6]])

In [93]:
arr = np.arange(2)
arr

array([0, 1])

In [94]:
arr.repeat(3)

array([0, 0, 0, 1, 1, 1])

In [97]:
np.tile(arr, (3,3))

array([[0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1]])

In [103]:
np.take(arr,[0])

array([0])

In [106]:
arr = np.arange(10) * 100
arr

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [107]:
inds = [7, 1, 2, 6]

In [108]:
arr[inds]

array([700, 100, 200, 600])

In [110]:
arr.put(inds, 42)
arr

array([  0,  42,  42, 300, 400, 500,  42,  42, 800, 900])

In [111]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
np.add.reduce(arr)

45

In [114]:
arr.sum()

45

In [121]:
arr = np.random.randn(5, 5)
arr

array([[-0.56644593,  0.03614194, -2.0749776 ,  0.2477922 , -0.89715678],
       [-0.13679483,  0.01828919,  0.75541398,  0.21526858,  0.84100879],
       [-1.44581008, -1.40197328, -0.1009182 , -0.54824245, -0.14461951],
       [ 0.35402033, -0.03551303,  0.56573831,  1.5456588 , -0.97423633],
       [-0.07034488,  0.30796886, -0.20849876,  1.03380073, -2.40045363]])

In [122]:
arr[::2].sort(1)

In [123]:
np.logical_and.reduce(arr[:, :-1] < arr[:, 1:], axis=1)

array([ True, False,  True, False,  True])

In [124]:
x, y = np.random.randn(3, 4), np.random.randn(5)

In [125]:
x.shape

(3, 4)

In [126]:
y.shape

(5,)

In [127]:
result = np.subtract.outer(x, y)

In [128]:
result.shape

(3, 4, 5)

In [131]:
arr = np.arange(3).repeat([1, 2, 2])
arr

array([0, 1, 1, 2, 2])

In [132]:
arr.shape

(5,)

In [130]:
np.multiply.outer(arr, np.arange(5))

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8],
       [0, 2, 4, 6, 8]])

In [134]:
np.arange(5).shape

(5,)

In [133]:
np.multiply.outer(arr, np.arange(5)).shape

(5, 5)

In [136]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [137]:
np.add.reduceat(arr, [0, 5, 8])

array([10, 18, 17], dtype=int32)

In [139]:
arr = np.multiply.outer(np.arange(4), np.arange(5))
arr

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12]])